import { createAsyncThunk } from "@reduxjs/toolkit";
import { renderChatMessage } from "core/util/messageContent";
import { selectSelectedChatModel } from "../slices/configSlice";
import { compactHistory } from "../slices/sessionSlice";
import { ThunkApiType } from "../store";

const SUMMARY_MAX_TOKENS = 1000;

const SUMMARY_INSTRUCTIONS =
  "Summarize the conversation below so the summary alone can replace the " +
  "full history and the assistant can keep working from it with no loss of " +
  "important context. Preserve: the original task/goal, key decisions made, " +
  "file paths that were read or edited and their current state, commands " +
  "that were run and what they returned, and anything still unresolved. Be " +
  "concise, but do not drop information the assistant needs to keep working " +
  "correctly. Write it as a direct recap of what happened, not as " +
  "commentary about summarizing.";

/**
 * Replaces the whole session history with a single condensed recap,
 * generated by the model itself
 */
export const compactSessionHistoryThunk = createAsyncThunk<
  void,
  undefined,
  ThunkApiType
>("session/compactHistory", async (_, { dispatch, extra, getState }) => {
  const state = getState();
  const history = state.session.history;

  if (history.length === 0) {
    return;
  }

  const selectedChatModel = selectSelectedChatModel(state);
  if (!selectedChatModel) {
    throw new Error("No model selected");
  }

  const transcript = history
    .map(
      (item) =>
        `${item.message.role.toUpperCase()}: ${renderChatMessage(item.message)}`,
    )
    .join("\n\n");

  const result = await extra.ideMessenger.request("llm/complete", {
    prompt: `${SUMMARY_INSTRUCTIONS}\n\n${transcript}`,
    completionOptions: { maxTokens: SUMMARY_MAX_TOKENS },
    title: selectedChatModel.title,
  });

  if (result.status === "error") {
    throw new Error(result.error);
  }

  dispatch(compactHistory({ summary: result.content }));
});
